id = "vue-theme"
name = "Vue Theme"
schema_version = 1
version = "0.0.1"
authors = ["ColasssNotMe <ecyw7355608@gmail.com>"]
description = "A port of Vue Theme from VSCode"
repository = "https://github.com/ColasssNotMe/vue-theme-zed"
